name: student-api

on:
  push:
    branches:
      - main
    paths:
      - 'src/Services/Student/**'
      - '.github/workflows/student-api.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/Services/Student/**'
      - '.github/workflows/student-api.yml'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_VERSION: 8.0.x
  DOTNET_QUALITY: 'preview'

jobs:
  BuildForPR_Linux:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          dotnet-quality: ${{ env.DOTNET_QUALITY }}
      - name: Restore dependencies
        run: |
          dotnet restore src/Services/Student/Student.API/Student.API.csproj
      - name: Build
        run: |
          dotnet build src/Services/Student/Student.API/Student.API.csproj --no-restore
  
  BuildLinux:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          dotnet-quality: ${{ env.DOTNET_QUALITY }}
      - name: Restore dependencies
        run: |
          dotnet restore src/Services/Student/Student.API/Student.API.csproj
      - name: Build
        run: |
          dotnet build src/Services/Student/Student.API/Student.API.csproj --no-restore
